### ISSUE TITLE
Create TODO list

### ISSUE THREAD

**Issue by KeizerDev** [iLexiconn/Magister.java#1]
I would like to improve the Magister.java library but is there something like a todo list?

PS. can you give some example code for how to use the library. This will make it more accessible for us all. 

Keep up the good work!

**Comment by iLexiconn** [comment]
I'll create some kind of issue todo system right now =)
You can find a small example here: https://github.com/iLexiconn/Magister.java/blob/master/src/test/java/net/ilexiconn/magister/Test.java

**Comment by KeizerDev** [comment]
Alright, that's what I was looking for!
