### ISSUE TITLE
Absence/Presence

### ISSUE THREAD

**Issue by JWolvers** [iLexiconn/Magister.java#10]
This seems to be not so hard to implement.

**Comment by KeizerDev** [comment]
I'll implement it now.

**Comment by KeizerDev** [comment]
Should I also implement `absentieperioden` or should I skip it and just use the current school year?

**Comment by iLexiconn** [comment]
I think only the current school year is enough.

**Comment by KeizerDev** [comment]
:+1:

**Comment by JWolvers** [comment]
Well I personally think you should implement it since is an api and  You never know the end user's use case will be. But that is just my suggestion

**Comment by iLexiconn** [comment]
Very true, but why would absences from the previous year be relevant?

**Comment by JWolvers** [comment]
Idk to calculate your absence over a time span and display it in a graph?

**Comment by KeizerDev** [comment]
Just open another issue for that

**Comment by KeizerDev** [comment]
#20
