### ISSUE TITLE
Do a codewise check for privileges 

### ISSUE THREAD

**Issue by KeizerDev** [iLexiconn/Magister.java#13]
I know my school doesn't support `berichten` and uses their own system. I'm developing with another Magister account but we should create a fallback and never assume that something exist or is accessible. JFYI

**Comment by KeizerDev** [comment]
I know there are also schools who have blocked showing absence for example

**Comment by iLexiconn** [comment]
How do we check if something is accessible or not?

**Comment by KeizerDev** [comment]
I guess you removed your comment because you already knew it.
If not we should simply check the privileges on login :) 

``` java
            System.out.println("========= Privileges =========");
            for (Privilege privilege : magister.profile.privileges) {
                System.out.println(privilege.name);
            }
```

**Comment by iLexiconn** [comment]
Yeah,  I'll fix it asap.
