### ISSUE TITLE
Crash on importing library

### ISSUE THREAD

**Issue by KeizerDev** [iLexiconn/Magister.java#16]
Those imports are not found:

``` java
import org.apache.http.client.cache.HttpCacheContext;
import org.apache.http.impl.client.cache.CachingHttpClientBuilder;


Error:(49, 53) java: cannot find symbol
  symbol:   variable CachingHttpClientBuilder
  location: class net.ilexiconn.magister.util.HttpUtil
```

**Comment by iLexiconn** [comment]
Add `org.apache.httpcomponents:httpclient-cache:4.5.1` to the dependencies

**Comment by KeizerDev** [comment]
Cool, thanks! :)

Ps. why do I have to do it this way and why does it not comes with `./gradlew build`?

**Comment by iLexiconn** [comment]
What do you mean? You can just add that line to the grade dependencies.

**Comment by JWolvers** [comment]
He means why dont we not include our dependencies in our jar file?

**Comment by iLexiconn** [comment]
Shh, he edited his comment. I didn't set it up yet, why would I when it not nearly ready for a release? ;)

**Comment by JWolvers** [comment]
touché 😑

**Comment by KeizerDev** [comment]
Lol, yeah. 
I had to add it manually in my IDE
