### ISSUE TITLE
Send messages

### ISSUE THREAD

**Issue by KeizerDev** [iLexiconn/Magister.java#17]

**Comment by KeizerDev** [comment]
Lol @MrWolvetech, thanks! Had not that much time to implement it my own..

**Comment by KeizerDev** [comment]
@iLexiconn So we are gonna to finish the milestone earlier than expected?

**Comment by JWolvers** [comment]
Well, i didn't have much to do so.

**Comment by JWolvers** [comment]
And i think so, we are quite far.

**Comment by iLexiconn** [comment]
There's a big chance we will! :)
