### ISSUE TITLE
Implement attachment

### ISSUE THREAD

**Issue by KeizerDev** [iLexiconn/Magister.java#18]

**Comment by iLexiconn** [comment]
Can we still add this to 0.1.0? @KeizerDev

**Comment by JWolvers** [comment]
depends on when you want to release it. I can try to implement it, doesn't look that hard.

**Comment by iLexiconn** [comment]
Somewhere next month.

**Comment by JWolvers** [comment]
Than yes

**Comment by KeizerDev** [comment]
You can assign it to @MrWolvetech than, haven't had that much time to work on it at all.

**Comment by iLexiconn** [comment]
Only one more thing to do; Beta testing!
