### ISSUE TITLE
Return Date object instead of String for every time related object

### ISSUE THREAD

**Issue by KeizerDev** [iLexiconn/Magister.java#19]
When I have something like `2014-07-31T22:00:00.0000000Z` I rather want a Date object than just a plain String, just implement the following format:   

```
new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss")
```

**Comment by JWolvers** [comment]
There is a method in the appointment class that does just that.

**Comment by iLexiconn** [comment]
`Appointment#appointmentDateToDate()`

**Comment by KeizerDev** [comment]
Ok, didn't saw that. 
We still should migrate that to a helper class because we have to use that on nearly every page.

**Comment by JWolvers** [comment]
True

**Comment by iLexiconn** [comment]
:+1:
