### ISSUE TITLE
Split up privileges

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#27]

**Comment by KeizerDev** [comment]
What do you mean by split up? In a separate class?

**Comment by iLexiconn** [comment]
Yeah, the Magister class is pretty messy right now.

**Comment by iLexiconn** [comment]
This is what I have right now:

``` java
System.out.println("=========== Grades ===========");
for (Grade grade : magister.getHandler(GradeHandler.class).getGrades(true, false, true)) {
    System.out.println(grade.course.name + ": " + grade.grade);
}
```

**Comment by KeizerDev** [comment]
Yeah that's cool! But what if i use it as an library? Can i still access
that class or do I have to implement it myself?

**Comment by KeizerDev** [comment]
Lol, i mean, it's pretty weird for me tot use `GradeHandler.class`

**Comment by iLexiconn** [comment]
It's shipped with the library, ofcourse.

**Comment by KeizerDev** [comment]
Are you going to migrate everything? If so, i'll wait a bit with contributing so we get less conflicts.

**Comment by iLexiconn** [comment]
Just add everything to the Magister file for now. :)
