### ISSUE TITLE
ELO

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#28]

**Comment by iLexiconn** [comment]
I can't test the other 3 items, because they're all empty for me. Can someone else please take a look at this?

**Comment by JWolvers** [comment]
I can take a look but that wont be until tomorrow/Mondayish

**Comment by KeizerDev** [comment]
@iLexiconn Just contact me by email, I have some backup accounts for that!

**Comment by iLexiconn** [comment]
@KeizerDev Sent you the email _wink_ _wink_

**Comment by KeizerDev** [comment]
@iLexiconn check your mail :wink:

**Comment by KeizerDev** [comment]
@iLexiconn are they still working? I got like 1000 more if needed.

**Comment by JWolvers** [comment]
How the f*ck did you acquire all those!?

**Comment by KeizerDev** [comment]
Let's say, good preparations before leaving school ;)

**Comment by iLexiconn** [comment]
@KeizerDev Didn't test them yet, but I'm sure they'll work. :)

**Comment by KeizerDev** [comment]
@iLexiconn is this really necessary for the 0.1.0 milestone? Let's make finnish our milestone as fast as possible and keep this of the 0.1.1 so we got at least something which people can use.

**Comment by iLexiconn** [comment]
:+1:

**Comment by KeizerDev** [comment]
And make multiple issues for it instead of one because of the `ELO` tag.
