### ISSUE TITLE
Create snapshot repo

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#29]
I already have the repo, but I don't know how I can generate the snapshot jars.

**Comment by JWolvers** [comment]
Use jenkins

**Comment by iLexiconn** [comment]
Can I use jenkins jars as dependency?

**Comment by JWolvers** [comment]
I believe you can

**Comment by iLexiconn** [comment]
Tried it, but I can't get it to work, Is there no way to do this with gradle?

**Comment by JWolvers** [comment]
https://github.com/codepath/android_guides/wiki/Building-Gradle-Projects-with-Jenkins-CI
This might help you

**Comment by iLexiconn** [comment]
I know how to build gradle projects with Jenkins, but I'm pretty sure I can use the default configuration as maven repo.

**Comment by JWolvers** [comment]
I am pretty sure you will need a plugin for that
