### ISSUE TITLE
JUnit support

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#30]

**Comment by iLexiconn** [comment]
Maybe we can use one of @KeizerDev's accounts?

**Comment by KeizerDev** [comment]
Sure :+1:

**Comment by iLexiconn** [comment]
@KeizerDev Can you change the system propereties with an actual account? The tests can't find the properties on Travis for some reason.

**Comment by KeizerDev** [comment]
Where do I have to place it exactly?

**Comment by iLexiconn** [comment]
https://github.com/iLexiconn/Magister.java/blob/master/src/test/java/net/ilexiconn/magister/ProfileTest.java#L41

**Comment by KeizerDev** [comment]
Just hardcode an account?

**Comment by iLexiconn** [comment]
Yeah, why not.

**Comment by KeizerDev** [comment]
Lol, I have also a helpdesk account xd

**Comment by KeizerDev** [comment]
Name: `Obama`

**Comment by KeizerDev** [comment]
@iLexiconn check your mail.
