### ISSUE TITLE
Migrate to HttpUrlConnection

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#31]

**Comment by KeizerDev** [comment]
Can you be more clear? I can implement it right away for android. You just have to run it on another thread instead of the ui thread.

**Comment by iLexiconn** [comment]
The BufferedImage and ImageIO classes can't isn't part of the android sdk. And maybe use the android http stuff as well.

**Comment by KeizerDev** [comment]
You can use `FileOutputStream`. I used it to store images on Android.

**Comment by iLexiconn** [comment]
I don't want to store it. It's used to get the profile picture. I also can't get the httpclient to work in Android 6.0+

**Comment by KeizerDev** [comment]
Could you make an test repo or branch for Android? I'll take a look at it

**Comment by iLexiconn** [comment]
Done. :)

**Comment by KeizerDev** [comment]
How do you exactly want to return the profile picture? There are so many
ways

**Comment by iLexiconn** [comment]
Er, just an image. :p

**Comment by KeizerDev** [comment]
So, `FileOutputStream`.

**Comment by KeizerDev** [comment]
I mean a test project for Android. Not really a development branch

**Comment by iLexiconn** [comment]
Sure. :p

**Comment by iLexiconn** [comment]
Whoops missed that message. I'll create one in a few mins.

**Comment by JWolvers** [comment]
There is no more httpclient in android 6.0 and up

**Comment by iLexiconn** [comment]
I know, that's why I tested it on that version.

**Comment by JWolvers** [comment]
And it doesn't fall back on urlhttpconnention?

**Comment by iLexiconn** [comment]
I'm talking about the HttpClient stuff.

**Comment by JWolvers** [comment]
Yeah but if the library is used on android, it should fall back on using urlhttpconnention instead of using httpclient.

**Comment by JWolvers** [comment]
I'm sorry i already get what you wete talking about. I will add this to my todo list for tomorrow.

**Comment by iLexiconn** [comment]
:+1:

**Comment by KeizerDev** [comment]
Lol, why don't you just compile it with a lower version?

**Comment by KeizerDev** [comment]
The lib is gone maybe, but that doesn't mean that older version won't run.

**Comment by JWolvers** [comment]
Because than it will crash on android 6.0+ because they cant find the class

**Comment by iLexiconn** [comment]
I want this lib to be future-ready. You never know when they are going to remove it completely.

**Comment by KeizerDev** [comment]
http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client

**Comment by KeizerDev** [comment]
Got a fix for it.

**Comment by JWolvers** [comment]
Please dont let it be just adding:

useLibrary 'org.apache.http.legacy'

To the gradle file 😕

**Comment by KeizerDev** [comment]
Yeah.. :smile:

**Comment by JWolvers** [comment]
Well that's not really a 'fix'

**Comment by KeizerDev** [comment]
I agree, let's migrate to `HttpURLConnection` than.

**Comment by JWolvers** [comment]
Only for android or also for normal desktop use?

**Comment by iLexiconn** [comment]
Let's take the easy path and do both.

**Comment by KeizerDev** [comment]
I agree with that. Let's keep it as universal as possible

**Comment by MrWolvetech** [comment]
Well we already switch to urlconnection on android now, well for the httputil part at least. So it wont be to hard to separate them.

**Comment by JWolvers** [comment]
Ok them I will migrate every thing to HttpUrlConnection

**Comment by KeizerDev** [comment]
Cool :+1:

**Comment by JWolvers** [comment]
👍

**Comment by iLexiconn** [comment]
Well this still doesn't fix the BufferedImage stuff.

**Comment by JWolvers** [comment]
Yes i forgot

**Comment by JWolvers** [comment]
We can return an object containing a drawable or a buffered image depending on which os we are running.

**Comment by KeizerDev** [comment]
Yeah, just return an universal type of object.

**Comment by JWolvers** [comment]
Well there is none. So we will have to create a wrapper.
