### ISSUE TITLE
Session returns 400

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#38]
https://github.com/iLexiconn/Magister.java/blob/master/src/main/java/net/ilexiconn/magister/util/HttpUtil.java#L57

**Comment by JWolvers** [comment]
Conn.doInput(true) might help. Not sure though.

**Comment by iLexiconn** [comment]
That's already there.

**Comment by JWolvers** [comment]
Only doOutput is there? Or is it's default true?

**Comment by JWolvers** [comment]
I already know; we dont set the session cookie

**Comment by iLexiconn** [comment]
`setDoOutput` is already there. Can I assign this to you then?

**Comment by JWolvers** [comment]
Yeah I will try to sort it out

**Comment by iLexiconn** [comment]
Maybe try putting `conn.connect();` before the return statement?

**Comment by JWolvers** [comment]
Well I get a 400 bad request response from my magister??

**Comment by iLexiconn** [comment]
@KeizerDev

**Comment by iLexiconn** [comment]
Yup, me too.

**Comment by KeizerDev** [comment]
aawh

**Comment by KeizerDev** [comment]
Wait, I haven't followed the conversation

**Comment by iLexiconn** [comment]
There's something wrong wit the POST method.

**Comment by JWolvers** [comment]
Yes for one it is't send in json, sorry my fault. But that is apparently not the only issue as i have fixed that on my side.

**Comment by iLexiconn** [comment]
Can you commit the updated code please? :)

**Comment by iLexiconn** [comment]
Are you sure you should send the data as json? I don't think the old code did that.

**Comment by KeizerDev** [comment]
Same problem, on every school.

**Comment by KeizerDev** [comment]
LOL

**Comment by KeizerDev** [comment]
Just `System.out.println(parameters);`

**Comment by KeizerDev** [comment]
Look at that nice parameters: `Wachtwoord=BLEEP&Gebruikersnaam=BLEEP&`

**Comment by iLexiconn** [comment]
I don't get it.

**Comment by KeizerDev** [comment]
EDIT: Sorry for not checking my answer.

**Comment by iLexiconn** [comment]
Now I'm even more confused.

**Comment by JWolvers** [comment]
now it gives an 500 response?

**Comment by KeizerDev** [comment]
@MrWolvetech where are you sending the parameters?

**Comment by JWolvers** [comment]
https://github.com/iLexiconn/Magister.java/blob/master/src/main/java/net/ilexiconn/magister/util/HttpUtil.java#L57

**Comment by iLexiconn** [comment]
On another note, maybe we should migrate to `HttpsURLConnection`

**Comment by KeizerDev** [comment]
Lol, wait. How does the Magister auth actually works?
When doing it returns a `400 badrequest` too: 

``` bash
curl -X POST -d '{"Wachtwoord":"PASS","Gebruikersnaam":"USER"}' https://SCHOOL.magister.net/api/sessies -i
```

**Comment by KeizerDev** [comment]
They changed it soo many times that I'm lost keeping track on it.

**Comment by KeizerDev** [comment]
Ah, it's still the delete/validate way.

**Comment by JWolvers** [comment]
so the httpDelete isn't working?

**Comment by iLexiconn** [comment]
Fixed it, will commit in a sec.

**Comment by JWolvers** [comment]
Nice :+1:

**Comment by KeizerDev** [comment]
Nice :)
