### ISSUE TITLE
Calendar support

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#4]

**Comment by JWolvers** [comment]
I'll add support for adding and deleting personel appointments tomorrow. I've gotten adding all figured out, but my packet sniffer seems to be unable to pick up http delete requests.

**Comment by iLexiconn** [comment]
:+1:

**Comment by KeizerDev** [comment]
Not that hard: 

``` bash
curl 'https://SCHOOL.magister.net/api/personen/PERSONID/afspraken/ID' -X DELETE -H 'Cookie: SESSION_ID=' 
```

**Comment by JWolvers** [comment]
I already suspected it was that, just wasn't able to test it yet.

**Comment by KeizerDev** [comment]
No problem, Magister isn't always that weird. :smiley:
