### ISSUE TITLE
Creating appointment returns 400

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#41]

**Comment by JWolvers** [comment]
I finally found the error magister returns: {"Message":"Type: Er is een ongeldig afspraaktype opgegeven."} so i guess i'll be fixing this

**Comment by iLexiconn** [comment]
:+1:

**Comment by JWolvers** [comment]
Fixed it i will do some clean up and the commit, or should i make an pull request?

**Comment by iLexiconn** [comment]
Please make it a pull request, like @KeizerDev does.

**Comment by JWolvers** [comment]
:+1:
