### ISSUE TITLE
Magister changed Inlog method again :(

### ISSUE THREAD

**Issue by JWolvers** [iLexiconn/Magister.java#42]
Well Magister changed Inlog method again :(

**Comment by KeizerDev** [comment]
_derp_

**Comment by iLexiconn** [comment]
It still works for me?

**Comment by KeizerDev** [comment]
@iLexiconn here too. I know Magister is doing some of those thing per school. 

@MrWolvetech, can you show me your Magister version by copying the output of: https://SCHOOL.magister.net/api/versie

**Comment by JWolvers** [comment]
{"ApiVersie":"1.27.42942.6","CoreVersie":"1.27.41852.18","DatabaseVersie":"5.6.50.0","ProductVersie":"6.0.27","ReleaseDatum":"2015-12-08T11:01:00.0399281Z"}

**Comment by KeizerDev** [comment]
Lol, yeah. My `ReleaseDatum` is like last month.. Stupid Magister, just update it everywhere or do not.

**Comment by JWolvers** [comment]
they changed the structure of links inside the login respones, fix is as easy as removing `Links[] links` object form `Session`
