### ISSUE TITLE
Make the Magister class Parcelable

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#43]
Or is there a better way to transfer the object from one activity to another?

**Comment by JWolvers** [comment]
Parcelable is the best way. Just make sure you make an seperate class that extends Magister and implements Parcable so we remain compatible with non android applications.

**Comment by iLexiconn** [comment]
I don't think gradle can compile errored code. Maybe we can add it as some kind of special dependency.

**Comment by JWolvers** [comment]
library so we can build again :)
https://drive.google.com/open?id=0B76J7JS4b2vVS09sR2xZYllseVE

include it in your project

**Comment by iLexiconn** [comment]
If you can give me access to the file. :p

**Comment by JWolvers** [comment]
Oops try again
