### ISSUE TITLE
`BerichtSoort` isn't always `Bericht`

### ISSUE THREAD

**Issue by JWolvers** [iLexiconn/Magister.java#44]
It can also be `Mededeling` now it throws a `FileNotFoundException` if it is a mededeling
https://github.com/iLexiconn/Magister.java/blob/master/src/main/java/net/ilexiconn/magister/handler/MessageHandler.java#L113

**Comment by iLexiconn** [comment]
You fixed this, right?

**Comment by KeizerDev** [comment]
No. Look at the source, there is still `Bericht` hardcoded. I will take a look at it

**Comment by JWolvers** [comment]
only inside `Test.java` still needs proper fixing

**Comment by KeizerDev** [comment]
We should do a check on `"Soort": ​1`
