### ISSUE TITLE
The study array isn't getting parsed (Parcel)

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#45]

**Comment by JWolvers** [comment]
Can you give some more information? I am not able to replicate your issue.

**Comment by iLexiconn** [comment]
https://github.com/iLexiconn/Magister.java/blob/master/src/main/java/net/ilexiconn/magister/ParcelableMagister.java#L60

**Comment by iLexiconn** [comment]
https://media.ilexiconn.net/uBrTpRj.txt

**Comment by JWolvers** [comment]
did you try just using Serializable?
Serializable also works with arrays

**Comment by iLexiconn** [comment]
We have to somehow make it also a Parcelable.

**Comment by JWolvers** [comment]
so you tried:
`studies = (Study[]) in.readSerializable();` and
`dest.writeSerializable(studies);`

**Comment by iLexiconn** [comment]
Yes I did, and it didn't work.

**Comment by JWolvers** [comment]
Not pretty but should work.

**Comment by iLexiconn** [comment]
:+1:
