### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#46]
Is anyone interested in helping me with my new magister android app? I already have some things done, I can show you some screenshots of you want.
The app is called Hipster. I already have a repo for it, but it's currently empty.

**Comment by JWolvers** [comment]
Sure i would live to help, but got some things I have to take care of first, Namely finishing my `Profiel Werkstuk`

**Comment by KeizerDev** [comment]
Lol, i'm also planning to totally recreate `Mister` by calling it `Magist` and use this library instead of my crappy implementation.

**Comment by JWolvers** [comment]
Well lets work together

**Comment by iLexiconn** [comment]
Here's a screenshot of my current progress. As you probably can see, it's my first Android application I've ever made. :p
![device-2015-12-09-193509](https://cloud.githubusercontent.com/assets/5201999/11694759/245ab51c-9eac-11e5-8ad1-90b3147548a0.png)
(Johanna is just a test person)

**Comment by KeizerDev** [comment]
Lol nice :p

**Comment by JWolvers** [comment]
doesn't look that bad :)

**Comment by iLexiconn** [comment]
Just uploaded the code to https://github.com/iLexiconn/Hipster

**Comment by KeizerDev** [comment]
@iLexiconn, Looks pretty clean!

**Comment by iLexiconn** [comment]
Thanks. :)
