### ISSUE TITLE
Unable to remove appointments

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#49]

**Comment by JWolvers** [comment]
Works for me

**Comment by iLexiconn** [comment]
Did you sync your code with master?

**Comment by JWolvers** [comment]
Something has changed since the last time i tried, will take an look at it tonight.

**Comment by iLexiconn** [comment]
I know, I changed the url thingy. I tried using the appointment ID instead.

**Comment by JWolvers** [comment]
Well using the appointment id still works for me.

**Comment by JWolvers** [comment]
can you show me your code?

**Comment by iLexiconn** [comment]
I'm using the test cases, it just leaves the test appointment without removing it.

**Comment by JWolvers** [comment]
Well from what i can see you are creating an appointment with equel start and end dates, which magister doesn't like.

**Comment by iLexiconn** [comment]
Already fixed that.

**Comment by JWolvers** [comment]
On android?

**Comment by iLexiconn** [comment]
I fixed the test, it's adding the appointment.

**Comment by JWolvers** [comment]
Well i understood that part, I was just wondering if you were using android. I know it has some issues regarding senging http Delete Requests

**Comment by iLexiconn** [comment]
Oh, no. I'm just running on Windows.

**Comment by JWolvers** [comment]
I found your issue. the id of every personel is 0 because the id is assignd by the server. I can set the id to the correct one, but I'll have to parse some stuff again and you didn't seem to like that.

**Comment by iLexiconn** [comment]
Well go ahead. :)
