### ISSUE TITLE
Message support

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#5]

**Comment by KeizerDev** [comment]
You can assignee this issue to me, I'll start working on it tomorrow.

I know how the sending protocol of Magister works, it uses an UUID for each message.
I have quite some experience working with it (https://github.com/Vogeltak/magister-message-spam/).

**Comment by iLexiconn** [comment]
I'll add you to the repo then, I hope you won't do any bad stuff. :P

**Comment by KeizerDev** [comment]
Cool :wink:

**Comment by KeizerDev** [comment]
I had not that much time today, will work on it asap.

**Comment by KeizerDev** [comment]
Still got some todo's:
- [ ] Post a message
- [ ] Create inner array helpers

**Comment by iLexiconn** [comment]
In the current system, `Message` and `SingleMessage` are exactly the same. Why?

**Comment by KeizerDev** [comment]
Nope, they are not

**Comment by KeizerDev** [comment]
`SingleMessage` has `inhoud` and `bijlagen` you have to do a single query to see those.

**Comment by iLexiconn** [comment]
Oh, right, okay. :)

**Comment by KeizerDev** [comment]
I think it's better to specify issues more rather than leave it as an too big subject, so we have more clear whats done and what have to be done to get to the milestone.
