### ISSUE TITLE
0.1.0

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#56]
Is the API ready for its first release? @KeizerDev @MrWolvetech

**Comment by KeizerDev** [comment]
Let's first make a changelog of what it's able to do and what have to be done in the `0.1.1` version and up.

**Comment by iLexiconn** [comment]
I have no idea how we're going to list it in a nice way.

**Comment by JWolvers** [comment]
We should also make the wiki page with some simple example code.

**Comment by KeizerDev** [comment]
I know how, http://keepachangelog.com/

**Comment by KeizerDev** [comment]
## [0.1.0] - 2015-12-15

### Added
- Implemented support for grades.
- Implemented creating and deleting personal appointment.
- etc.

### Changed
-

**Comment by iLexiconn** [comment]
https://github.com/iLexiconn/Magister.java/commit/8f29fc19526aab35df13c2a06b2e0419f260ab62

**Comment by KeizerDev** [comment]
Yeah, that's pretty good. Next step, reorganize the `README.md`.

**Comment by iLexiconn** [comment]
Can I leave that to you? :p

**Comment by KeizerDev** [comment]
Yeah :+1:

**Comment by JWolvers** [comment]
Maybe we should add a wiki?

**Comment by iLexiconn** [comment]
https://magister.ilexiconn.net/Main_Page

**Comment by iLexiconn** [comment]
Compiling 0.1.0 right now.

**Comment by JWolvers** [comment]
👍
