### ISSUE TITLE
Backup Login Method

### ISSUE THREAD

**Issue by JWolvers** [iLexiconn/Magister.java#59]
I have this idea of having a backup login method for if the default one fails, this will come in handy if Magister changes the login method again. I envisioned it like this: default method fails, so in our backup method we just go to the school's magister url, fill in the form programmatically and execute the following javascript: `loginForm.getElementsByClassName('btn-primary3')[0].click()` which simulates a click on the normal login button on the magister site, than after we succesfully logged in, we extract the Session_ID cookie and use it in our own library :)

What do you guys think?

**Comment by iLexiconn** [comment]
If you can do it before new year, sure. :p

**Comment by JWolvers** [comment]
I'll try

**Comment by KeizerDev** [comment]
We need [jsoup](http://jsoup.org/) for that

**Comment by iLexiconn** [comment]
Please don't any more dependencies :(

**Comment by KeizerDev** [comment]
Yeah, it's pretty hard to do without I guess, maybe @MrWolvetech knows how..

**Comment by JWolvers** [comment]
Well for Java yes, but we can implement it as an android only feature since it wont require a library on android.

**Comment by iLexiconn** [comment]
I don't think we need it for the first release. Can we move this feature over to 0.1.1?

**Comment by JWolvers** [comment]
Sure

**Comment by JWolvers** [comment]
We dont need a library for java either we can use webeninge form javafx, the feature will only be able to run on java 8 tough.

**Comment by iLexiconn** [comment]
Let's not do it then. I want this API to work on all Java versions.
