### ISSUE TITLE
Remove GSON dependency

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#65]

**Comment by JWolvers** [comment]
Aka build a fat jar?

**Comment by iLexiconn** [comment]
No, migrate to the default java json tools

**Comment by JWolvers** [comment]
But gson is faster, if I'm not mistaken.

**Comment by KeizerDev** [comment]
Wait, lets first finnish the other issues so we got the whole api packed in a lib and than go for a smaller library.
